export const STATIC_DOMAIN: string = process.env.STATIC_DOMAIN || ''
export const MEEY_SHARE_API_URL: string = process.env.MEEY_SHARE_API_URL || ''
export const MEEEYID_SDK_URL: string = process.env.MEEEYID_SDK_URL || ''
export const MEDIA_API_URL: string = process.env.MEDIA_API_URL || ''
export const MEEY_SHARE_URL: string = process.env.MEEY_SHARE_URL || ''
export const CLIENT_ID: string = process.env.CLIENT_ID || ''
export const FB_APP_ID: string = process.env.FB_APP_ID || ''
export const APP_STORE_URL: string = process.env.APP_STORE_URL || ''
export const PLAY_STORE_URL: string = process.env.PLAY_STORE_URL || ''

export const SEO_NO_INDEX: boolean = process.env.SEO_NO_INDEX === 'true'
export const SEO_NO_FOLLOW: boolean = process.env.SEO_NO_FOLLOW === 'true'

export const TRACKING_SCROLL_LISTING: boolean = process.env.TRACKING_SCROLL_LISTING === 'true'

export const ONE_SIGNAL_APP_ID: string = process.env.ONE_SIGNAL_APP_ID || ''
export const ONE_SIGNAL_REST_API_KEY: string = process.env.ONE_SIGNAL_REST_API_KEY || ''
export const GTM_CODE: string = process.env.GTM_CODE || ''
export const FIREBASE_KEY: string = process.env.FIREBASE_KEY || ''
export const FIREBASE_DOMAIN_URI: string = process.env.FIREBASE_DOMAIN_URI || ''
